version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.openrewrite"
      - dependency-name: "org.glassfish.jaxb:jaxb-runtime"
