# sbm-support-rewrite
these components

The `sbm-support-rewrite` module provides these components

- `ProjectScanner` - to scan a project to a list of `Resource`s
- `RewriteProjectParser` - to parse the list of `Resource`s that belong to the build to OpenRewrite's AST representation
- `RecipeDiscovery` - to provide access to recipes found at possible locations (Jar, classpath, ...)

## Parse a project

Use ProjectScanner to scan a given baseDir
[source,java]
....
Path baseDir = Path.of("...").toAbsolutePath.normalize();
List<Resource> resources = projectScanner.scan(baseDir);
....

Create ExecutionContext, it will be populated with messages during the parsing.
These messages are important for other recipes
[source,java]
....
ExecutionContext ctx = new InMemoryExecutionContext(t -> t.printStackTrace());
....

The RewriteParser parses a given baseDir to ORs AST
[source,java]
....
RewriteProjectParser parser = new RewriteProjectParser();
List<SourceFile> ast = parser.parse(baseDir, resources, ctx);
....

## Discover recipes
[source,java]
....
RecipeDiscovery discovery = new RewriteRecipeDiscovery();
List<String> activeRecipes = ...
List<Recipe> recipes = discovery.discoverFilteredRecipes(activeRecipes, properties);
....

## Run recipes
[source,java]
....
RecipeRun result = recipes.get(0).run(ast, ctx);
....


## Handle Recipe Result



The `OpenRewriteProjectParser` aims to provide the exact same parsing capabilities as the parsing in `rewrite-maven-plugin` and `rewrite-gradle-plugin`.

This allows parsing a given project to it's OpenRewrite AST representation and then provide the AST to OR recipes and visitors to run OpenRewrite recipes without requiring a build plugin.

## Running OpenRewrite recipes

### Scan the codebase

The `RewriteProjectParser` uses Spring's `Resource` abstraction to abstract from file system.
This allows testing without file access among other things.
The `ProjectScanner` allows to scan all resources under a  given `Path`.

[source,java]
....
@Component

public class ProjectScannerClient {
    public List<Resource> scan(Path baseDir) {

    }
}
@Autowired
private ProjectScanner scanner;

List<Resource> resources = scanner.scan(projectRoot);

....

### Parse the scanned resources

### Discover recipes

### Run recipe




[source,java]
....
import org.openrewrite.InMemoryExecutionContext;import org.openrewrite.LargeSourceSet;
import org.openrewrite.Recipe;
import org.openrewrite.internal.InMemoryLargeSourceSet
import org.springframework.sbm.recipes.RewriteRecipeDiscovery;
import java.util.List;import java.util.Optional;

@Component
@RequiredArgsConstructor
public class MyTool {

    // The parser is a Spring bean
    private final RewriteProjectParser parser;
    // RecipeDiscovery is a Spring bean
    private final RewriteRecipeDiscovery recipeDiscovery;
    // ProjectScanner is a Spring bean
    private final ProjectScanner projectScanner;

    public RecipeResult runRecipe(Path baseDir, String recipeName) {
        ExecutionContext ctx = new InMemoryExecutionContext();
        List<Resource> resources = projectScanner.scan(baseDir);
        List<SourceFile> ast = parser.parse(baseDir, resources, ctx);
        Xml.Document rootPom = findRootPom(ast);
        recipeDiscovery.discoverFilteredRecipe(rootPom, recipeName)
            .ifPresent(recipe -> recipe.run(new InMemoryLargeSourceSet(ast), ctx));
    }
}
....

[plantuml,"class-design","svg"]
....
class RewriteProjectParser {
    parse(..)
}

class MavenProjectParser {

}

MavenProjectParser ..> BuildFileParser
BuildFileParser ..> RewriteMavenMojoProjectParser

class GradleProjectParser {
}
....

Example code showing how to apply OpenRewrite's UpgradeSpringBoot_3_1 recipe

[source, java]
.....
import org.openrewrite.*;
import org.openrewrite.internal.InMemoryLargeSourceSet;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.core.io.Resource;
import org.springframework.sbm.parsers.ProjectScanner;
import org.springframework.sbm.parsers.RewriteMavenProjectParser;
import org.springframework.sbm.parsers.RewriteProjectParsingResult;
import org.springframework.sbm.recipes.RewriteRecipeDiscovery;

import java.nio.file.Path;
import java.util.List;
import java.util.Set;

/**
 * @author Fabian Krüger
 */
@SpringBootApplication
public class BootUpgrade implements CommandLineRunner {
    public static void main(String[] args) {
        SpringApplication.run(BootUpgrade.class, args);
    }

    @Autowired
    ProjectScanner scanner;
    @Autowired
    RewriteMavenProjectParser parser;
    @Autowired
    RewriteRecipeDiscovery discovery;

    @Override
    public void run(String... args) throws Exception {

        String path  = "demo-spring-song-app";
        Path baseDir = Path.of(path ).toAbsolutePath().normalize();
        System.out.println(baseDir);
        if(!baseDir.toFile().exists() || !baseDir.toFile().isDirectory()) {
            throw new IllegalArgumentException("Given path '%s' does not exist or is not a directory.".formatted(path));
        }
        List<Resource> resources = scanner.scan(baseDir, Set.of("**/.idea/**", "**/.DS_Store", "**/.git/**"));
        ExecutionContext ctx = new InMemoryExecutionContext(t -> {throw new RuntimeException(t);});
        RewriteProjectParsingResult parsingResult = parser.parse(baseDir/*, resources*/, ctx);
        String recipeName = "org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_1";
        List<Recipe> recipes = discovery.discoverRecipes();
        recipes.stream()
                .filter(r -> recipeName.equals(r.getName()))
                .forEach(r -> {
                    System.out.println("Applying recipe '%s'".formatted(r.getName()));
                    LargeSourceSet lss = new InMemoryLargeSourceSet(parsingResult.sourceFiles());
                    RecipeRun recipeRun = r.run(lss, ctx);
                    recipeRun.getChangeset().getAllResults().stream()
                            .map(Result::diff)
                            .forEach(System.out::println);
                });
    }
}
.....