---
platform: linux
inputs:
  - name: git-repo
outputs:
  - name: git-repo
#caches:
#  - path: gradle
#params:
#  CI: true
#  GRADLE_ENTERPRISE_URL: https://ge.spring.io
#run:
#  path: git-repo/ci/scripts/build-pr-project.sh
params:
  BRANCH:
  CI: true
  SKIP_PRIVILEGED: false
  DOCKER_HUB_MIRROR:
run:
  path: bash
  args:
    - -ec
    - |
      source /docker-lib.sh
      start_docker $DOCKER_HUB_MIRROR
      ${PWD}/git-repo/ci/scripts/build-pr-project.sh