---
platform: linux

inputs:
  - name: git-repo

outputs:
  - name: maven-files
    path: ~/target
  - name: .m2
    path: /root/.m2
  - name: .rewrite-cache
    path: ~/.rewrite-cache
  - name: .rewrite
    path: ~/.rewrite
  - name: git-repo
params:
  BRANCH:
  CI: true
  SKIP_PRIVILEGED: false
  DOCKER_HUB_MIRROR:
run:
  path: bash
  args:
    - -ec
    - |
      source /docker-lib.sh
      start_docker $DOCKER_HUB_MIRROR
      ${PWD}/git-repo/ci/scripts/build-project.sh
