---
platform: linux

inputs:
  - name: git-repo
  - name: .m2
  - name: maven-files
  - name: .rewrite-cache
  - name: .rewrite

outputs:
  - name: maven-files
    path: ~/target
  - name: git-repo

run:
  path: /bin/sh
  args:
    - "-c"
    - "cd git-repo && mvn test"