[[getting-started]]
= Getting Started

This section offers quick guidance on how to get started with using Spring Rewrite Commons.


## Adding the dependency
Currently only SNAPSHOT releases are available from https://repo.spring.io.
To access these, a repository must be added to the project pom.xml.

[source,xml]
.....
<repositories>
    <repository>
        <id>spring-snapshot</id>
        <url>https://repo.spring.io/snapshot</url>
        <releases>
            <enabled>false</enabled>
        </releases>
    </repository>
</repositories>
.....

Then the dependency can be retrieved.

[source,xml]
.....
<dependency>
    <groupId>org.springframwork.experimental</groupId>
    <artifactId>spring-rewrite-commons</artifactId>
    <version>0.1.0-SNAPSHOT</version>
</dependency>
.....

== Scan a project (optional)
`ProjectScanner` component scans a given `Path` to a list of ``Resource``s.
It filters out resources and directories matching any of the ignore patterns in `parser.ignoredPathPatterns`.

== Parse a project
`RewriteProjectParser` is provided as pring bean and parses a project to OpenRewrite LST.

The provided `parse(Path)` method can be used to parse a project under a given `Path` to OpenRewrite LST.

[source,java]
.....
@Autowired
RewriteProjectParser parser;

Path baseDir = ...
List<SourceFile> lst = parser.parse(baseDir);
.....

== ExecutionContext
OpenRewrite's `ExecutionContext` is populated during parsing and the settings are required for later recipe execution.
The `ExecutionContext` is provided as scoped Spring bean and can be injected into other Spring beans.
A new instance is created and populated with every parse.

NOTE: The ExecutionContext should always be injected and should not be created programmatically.

[source,java]
....
@Autowired
ExecutionContext ctx;
....

== Run a OpenRewrite recipe
The LST and the `ExecutionContext` from the parse is required to apply OpenRewrite recipes.
[source, java]
....
Recipe rewriteRecipe = ...
RecipeRun recipeRun = rewriteRecipe.run(new InMemoryLargeSourceSet(lst), executionContext)
....


== Discover and run recipes

OpenRewrite recipes can be discovered from classpath with `RewriteRecipeDiscovery` which is provided as Spring bean.

[source,java]
....
@Autowired
RewriteRecipeDiscovery discovery;

@Autowired
ExecutionContext ctx;
...
Recipe recipe = discovery.getRecipe("org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_1");
RecipeRun recipe = recipe.run(new InMemoryLargeSourceSet(ast), ctx));
....

== Use ProjectResourceSet
A successful recipe run will return the modified ``SourceFile``s.
Before another recipe can be applied to the AST the changed ``SourceFile``s need to be merged into the original list of ``SourceFile``s (the AST).
The `ProjectResourceSet` provides this capability.

[source,java]
....
@Component
public class SomeClass {

    @Autowired
    ProjectResourceSetFactory factory;

    @Autowired
    RewriteProjectParser parser;

    void method() {
        Recipe r1 = ...
        Recipe r2 = ...
        RewriteProjectParsingResult parsingResult = parser.parse(baseDir);
        List<SourceFile> sourceFiles = parsingResult.sourceFiles();
        ProjectResourceSet projectResourceSet = factory.create(baseDir, sourceFiles);
        projectResourceSet.apply(r1); // internally changes get merged back to AST
        projectResourceSet.apply(r2); // r2 applied against the AST with changes from r1
    }
}
....

== Write changes back to filesystem
The `ProjectResourceSetSerializer` can be used to write all changes (modify, delete, add) in `ProjectResourceSet` to the filesystem.

[source,java]
....
@Autowired
private ProjectResourceSetSerializer serializer;
...
public void method() {
    ...
    serializer.writeChanges(projectResourceSet);
}
....



== Listen to ParserEvents

``ParserEvent``s get published during parsing.
The events can be used to provide progress information to users.
This is especially useful when parsing large projects where parsing can take some time.


* `StartedParsingProjectEvent` - Gets published when the parsing started
* `ParsedResourceEvent` - Gets published  after every parsed pom or Java file
* `SuccessfullyParsedProjectEvent` - Gets published when the parsing was successful

[source,java]
.....
@EventListener(ParsedResourceEvent.class)
public void onParsedResourceEvent(ParsedResourceEvent event) {
    Parser.Input input = event.input();
    SourceFile sourceFile = event.sourceFile();
    log("parsed %s to %s".formatted(input.getRelativePath(), sourceFile.getClass().getName()));
}
.....