[[getting-started]]
= Getting Started

This section offers quick guidance to developers on how to get started using Spring Rewrite Commons.


////
== Create a Simple Spring Boot application
Spring Rewrite Commons is meant to be used in Spring Boot applications.
To create a blank Boot application, go to https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.2.0&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=spring-rewrite-commons-example&name=spring-rewrite-commons-example&description=Demo%20project%20for%20Spring%20Rewrite%20Commons&packageName=com.example.rewrite[start.spring.io,window=_blank] and press "generate" to download a basic Boot application.
////


== Add Repository
include::partials/snapshots-repository.adoc[]

== Add dependency
The dependency to Spring Rewrite Commons must be added to the build file.

include::partials/dependency-code.adoc[]

== Example Application
This dummy code of a Spring application shows how to use the components provided by Spring Rewrite Commons to parse
an application and write back the changes to the filesystem.

[source,java]
....
import org.springframework.beans.factory.annotation.Autowired;

@Component
public class MyMigrationApplication {

    @Autowired <1>
    private RewriteProjectParser parser;

    @Autowired
    private RewriteRecipeDiscovery discovery; <3>

    @Autowired
    private ProjectResourceSetFactory resourceSetFactory; <4>

    @Autowired
    private ProjectResourceSetSerializer serializer; <5>


    public void migrateToBoot3_1() {
        Path baseDir = ... <2>
        String recipeName = "org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_1";
        Recipe boot3Upgrade = discover.getByName(recipeName); <3>

        RewriteParsingResult result = parser.parse(baseDir); <4>
        List<SourceFile> lst = result.sourceFiles(); <5>
        ProjectResourceSet resourceSet = resourceSetFactory.create(baseDir, lst); <6>
        resourceSet.apply(boot3Upgrade); <7>
        serializer.writeChanges(resourceSet); <8>
    }
}
....
<1> All components are Spring beans and can be injected as such.
<2> The path of the project that should be migrated.
<3> `RewriteRecipeDiscovery` is used to discover an OpenRewrite recipe by name.
<4> `RewriteProjectParser` parses a given project to OpenRewrite LST.
<5> The result contains the list of ``SourceFile``s (the LST).
<6> `ProjectResourceSetFactory` can be used to create a `ProjectResourceSet`.
<7> The recipe is applied to the `ProjectResourceSet` which wraps the LST.
<8> `ProjectResourceSetSerializer` is used to serialize the changes to disk.

Read more about the xref:components.adoc[available components].
