- name: cn-spring-cloud-config-server
  description: Externalize properties to Spring Cloud Config Server
  condition:
    type: org.springframework.sbm.build.migration.conditions.NoDependencyExistMatchingRegex
    dependencies:
      - 'org\.springframework\.cloud\:spring-cloud-starter-config.*'

  actions:
    - type: org.springframework.sbm.build.migration.actions.AddMavenDependencyManagementAction
      condition:
        type: org.springframework.sbm.build.migration.conditions.NoDependencyExistMatchingRegex
        dependencies:
          - 'org\.springframework\.cloud'
      name: "add managed dependency to Maven"
      groupId: org.springframework.cloud
      artifactId: spring-cloud-dependencies
      version: 2020.0.4
      dependencyType: pom
      scope: import
      description: Add Spring Cloud dependency management section to buildfile.

    - type: org.springframework.sbm.build.migration.actions.AddDependencies
      condition:
        type: org.springframework.sbm.build.migration.conditions.NoExactDependencyExist
        dependency:
          groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-config
      dependencies:
        - groupId: org.springframework.cloud
          artifactId: spring-cloud-starter-config
          version: latest.release
      description: Add spring-cloud-starter-config dependency to build file.
      detailedDescription: |-
        This code snippet is going to be added to the <dependencies> section in pom.xml

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>

    - type: org.springframework.sbm.sccs.MigrateToSpringCloudConfigServer
      condition:
        type: org.springframework.sbm.common.migration.conditions.TrueCondition
      description: Create config project and copies relevant property files.

#    - type: org.springframework.sbm.actions.DisplayDescription
#      condition:
#        description: 'Dependency to spring-cloud-starter-config exists.'
#        type: org.springframework.sbm.conditions.AnyDeclaredDependencyExistMatchingRegex
#        dependencies:
#          - 'org\.springframework\.cloud\:spring-cloud-starter-config.*'
#      description: |-
#        A new project parallel to the scanned project was created.
#        This project is suffixed with '-config' and contains the properties files previously contained in the migrated project.
#        You need to push this project to a Git server and configure your Spring Cloud Config Server to access this Git project.
#        The 'application.properties' in the migrated project contains 'spring.config.import' property which must point to the Spring Cloud Config Server.
#        See https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_spring_cloud_config_client for further information.