---
anchors:
  git-repo-resource-source: &git-repo-resource-source
    uri: ((github-repo-uri)) # https://github.com/spring-projects-experimental/spring-boot-migrator
    username: ((github-repo-user)) # fabapp2
    password: none # ((github-ci-release-token))
    branch: ci
  docker-hub-mirror-vars: &docker-hub-mirror-vars
    docker-hub-mirror: ((docker-hub-mirror))
    docker-hub-mirror-username: ((docker-hub-mirror-username))
    docker-hub-mirror-password: ((docker-hub-mirror-password))
  registry-image-resource-source: &registry-image-resource-source
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    tag: ((milestone))
#    registry_mirror:
#      host: ((docker-hub-mirror))
#      username: ((docker-hub-mirror-username))
#      password: ((docker-hub-mirror-password))

resources:
  - name: git-repo
    type: git
    icon: github
    source:
      <<: *git-repo-resource-source
  - name: ci-image
    type: docker-image
    icon: docker
    source:
#      <<: *registry-image-resource-source
      repository: fkrueger096/spring-boot-migrator-ci
      tag: latest


#  - name: spring-boot-migrator-image
#    type: docker-image
#    source:
#      repository: othmankh/sbm
#      tag: 1.0.0

jobs:

#  - name: build-ci-images
#    plan:
#      - in_parallel:
##          - get: ci-image
#          - get: git-repo
#            trigger: true
#      - in_parallel:
#          - task: build-ci-image
#            privileged: true
#            file: git-repo/ci/tasks/build-ci-image.yml
#            output_mapping:
#              image: ci-image
#            vars:
#              ci-image-name: ci-image
#              <<: *docker-hub-mirror-vars
#      - in_parallel:
#          - put: ci-image
#            params:
#              image: ci-image/image.tar

  - name: spring-boot-migrator-build
    serial: true
    plan:
      - in_parallel:
          - get: ci-image
          - get: git-repo
            trigger: true
      - in_parallel:
          - task: build
            privileged: true
            image: ci-image
            file: git-repo/ci/tasks/maven-build/task.yml