version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./init/definitions.json:/etc/rabbitmq/definitions.json
