name: Java CI with Maven

on:
  push:
    branches: [ main, 'hacking/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build server
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build with Maven
      run: |
        cd server
        ./mvnw -B verify --file pom.xml
